version: '2.0'

services:

  mysql:
    image: mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./script/data:/code/scropt/data
      - ./script/data/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mongo:
    restart: always
    build: 
      context: .
      dockerfile: mongo-dockerfile
    environment:
      MONGO_INITDB_DATABASE: bookstore
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=booksotre.com
      - NGINX_PORT=80

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uwsgi --http 127.0.0.1:8000 --module app:create_app()'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - mysql
      - nginx
      - mongo
