version: '2.0'

services:

  mysql:
    image: mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./script/data/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mongo:
    restart: always
    build: 
      context: .
      dockerfile: mongo-dockerfile
    privileged: true
    volumes:
      - /home/caisi/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: bookstore
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
    links:
      - web

  bookstore:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      # - /etc/localtime:/etc/localtime  # 时区
    expose:
      - 8000
    links:
      - mysql
      - mongo
