version: '3'

services:

  mysql:
    image: mysql
    restart: always
    command: ['--default-authentication-plugin=mysql_native_password',
              mysql -uroot -proot bookstore < '/code/script/data/bookstore.sql
      ]
    volumes:
      - ./script/data:/code/scropt/data
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./scropt/data/bookstore:/code/script/data/booksotre/
    command: mongorestore -u root -p root -d bookstore --dir /code/script/data/bookstore/


  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=booksotre.com
      - NGINX_PORT=80

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uwsgi --http 127.0.0.1:8000 --module app:create_app()
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    links:
      - mysql
      - nginx
      - mongo