version: '2.0'

services:

  mysql_bs:
    image: mysql
    restart: always
    networks:
      - bookstore_net
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./script/data/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mongo:
    restart: always
    build: 
      context: .
      dockerfile: mongo-dockerfile
    privileged: true
    networks:
      - bookstore_net
    volumes:
      - /home/caisi/bookstore/script/data/mongo/init:/mongo/back
    environment:
      MONGO_INITDB_DATABASE: bookstore
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

#  nginx:
#    image: nginx
#    restart: always
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ~/nginx:/etc/nginx/conf.d/
#    ports:
#      - 80:80
    # depends_on:
    #   - bookstore
#    links:
#      - bookstore

  bookstore:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
      #- .:/code
      # - /etc/localtime:/etc/localtime  # 时区
    expose:
      - 8000
    links:
      - mysql_bs
      - mongo
    networks:
      - bookstore_net

networks:
  bookstore_net:
    driver: bridge
