version: '3'

services:

  mysql:
    image: mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: mongorestore -d bookstore --dir /code/script/data/bookstore/


  nginx:
    image: nginx
    volumes:
      - ./conf:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=booksotre.com
      - NGINX_PORT=80

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    links:
      - mysql
      - nginx
      - mongo